# Generated by Django 2.1.3 on 2018-11-23 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('hashtag', models.CharField(blank=True, max_length=50)),
                ('deadline', models.DateTimeField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_post_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-update_date', '-id'],
            },
        ),
    ]
